settings:
  title: 'Status Page'
  url: 'https://example.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: example-homepage # unique identifier
    name: Example.com
    description: 'Example homepage monitor' # default=empty
    url: 'https://example.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: cloudflare
    name: Cloudflare
    description: 'Cloudflare homepage'
    url: 'https://www.cloudflare.com/'
    method: GET
    expectStatus: 200
    linkable: true

  - id: github-status
    name: GitHub Status
    description: 'Status page for GitHub'
    url: 'https://www.githubstatus.com/'
    method: GET
    expectStatus: 200
    linkable: true
